config/routes.rb
WebRTC::Application.routes.draw do
  resources :meetings
	resources :rooms
	match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
  get "home/index"
  get "home/call"
  get "home/customer"
	get "home/tokbox"
	post 'voice' => 'home#voice'

	 root 'home#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/webhookable.rb
module Webhookable
	extend ActiveSupport::Concern
	def set_header
		response.headers["Content-Type"] = "text/xml"
	end

	def render_twiml(response)
		render text: response.text
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end

	def customer

	end


  
  def call
    @meeting = Meeting.find(params[:id])
    
		if params[:customer_name]
			@customer_name = params[:customer_name]
		end
		default_client = "demoperformer"
		@client_name = params[:client]
		if @client_name.nil?
			Rails.logger.info "Client is nil"
			@client_name = default_client
		end
		Rails.logger.info "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		Rails.logger.info @client_name
		TWILIO_INIT.allow_client_outgoing DEMO_APP_SID_TWILIO
		TWILIO_INIT.allow_client_incoming @client_name
		@token = TWILIO_INIT.generate
	end

	def voice
		params[:PhoneNumber]
		response = Twilio::TwiML::Response.new do |r|
			# Should be your Twilio Number or a verified Caller ID
			r.Dial :callerId => caller_id do |d|
				# # Test to see if the PhoneNumber is a number, or a Client ID. In
				# # this case, we detect a Client ID by the presence of non-numbers
				# # in the PhoneNumber parameter.
				if /^[\d\+\-\(\) ]+$/.match(number)
					d.Number(CGI::escapeHTML number)
				else
					d.Client number
				end
			end
		end
		response.text 
	end

	def tokbox

	end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
    render json: @meetings
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    render json: @meeting
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:performer_name, :performer_country, :duration, :time, :customer_name, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_filter :config_opentok,:except => [:index]
	def index
		@rooms = Room.where(:public => true).order("created_at DESC")
		@new_room = Room.new
	end

	def create
		session = @opentok.create_session request.remote_addr
		params[:room][:sessionId] = session.session_id

		@new_room = Room.new(params[:room])

		respond_to do |format|
			if @new_room.save
				format.html { redirect_to("/party/"+@new_room.id.to_s) }
			else
				format.html { render :controller => 'rooms',
									:action => "index" }
			end
		end
	end

	def party
		@room = Room.find(params[:id])

		@tok_token = @opentok.generate_token :session_id =>@room.sessionId     
	end

	private
	def config_opentok
		if @opentok.nil?
			@opentok = OpenTok::OpenTokSDK.new 22329432, "f03a315fc996dff095d697eb7949cbec1474c6ba"
		end
	end

end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
	require 'twilio-ruby'
	include Webhookable

	after_filter :set_header

	def voice
		response = Twilio::TwiML::Response.new do |r|
			r.Say 'Hey there. Congrats on integrating Twilio into your Rails 4 app.', :voice => 'alice'
			r.Play 'http://linode.rabasa.com/cantina.mp3'
		end
		render_twiml response
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/twillio_helper.rb
module TwillioHelper
end

app/views/home/call.html.haml
.container
  #call_id
    %center
      .row
        .col-md-12 
          %br
          #myPublisher 
          %br
          #countdown
          %br
          %button#hangup_button.call.btn-lg.btn-danger{onclick: "opentok_client_hangup(this.session);"}
            Hangup
          
   
  %div.well.pull-left.col-md-4
    %u
      %h4 Current Call
    
    %h3 #{@meeting.performer_name}
    %h4 #{@meeting.performer_country}
    %h5 Duration: #{@meeting.duration} minutes
    #session_duration{"data-duration" => "#{@meeting.duration}"}
    #session_performer_name{"data-performer-name" => "#{@meeting.performer_name}"}
    
      
      

app/views/home/customer.html.haml
.container
  #call_id#customer_video
    %center
      .row
        .col-md-12 
          %br
          #myPublisher 
          %br
          #countdown

app/views/home/tokbox.html.haml
%meta{content: "chrome=1", "http-equiv" => "X-UA-Compatible"}/

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebRTC</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	
  <%#= javascript_include_tag "//static.twilio.com/libs/twiliojs/1.1/twilio.min.js", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "http://static.opentok.com/webrtc/v2.0/js/TB.min.js", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	

  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :performer_name
    = f.text_field :performer_name
  .field
    = f.label :performer_country
    = f.text_field :performer_country
  .field
    = f.label :duration
    = f.datetime_select :duration
  .field
    = f.label :time
    = f.datetime_select :time
  .field
    = f.label :customer_name
    = f.text_field :customer_name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', @meeting
\|
= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
%h1 Listing meetings
%table
  %tr
    %th Performer name
    %th Performer country
    %th Duration
    %th Time
    %th Customer name
    %th Description
    %th
    %th
    %th

  - @meetings.each do |meeting|
    %tr
      %td= meeting.performer_name
      %td= meeting.performer_country
      %td= meeting.duration
      %td= meeting.time
      %td= meeting.customer_name
      %td= meeting.description
      %td= link_to 'Show', meeting
      %td= link_to 'Edit', edit_meeting_path(meeting)
      %td= link_to 'Destroy', meeting, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
%p#notice= notice

%p
  %b Performer name:
  = @meeting.performer_name
%p
  %b Performer country:
  = @meeting.performer_country
%p
  %b Duration:
  = @meeting.duration
%p
  %b Time:
  = @meeting.time
%p
  %b Customer name:
  = @meeting.customer_name
%p
  %b Description:
  = @meeting.description

= link_to 'Edit', edit_meeting_path(@meeting)
\|
= link_to 'Back', meetings_path